name: Publish

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true

      - name: Install espflash
        run: cargo install cargo-espflash

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Trim binary
        run: cargo espflash save-image --chip esp32s3 -s 4mb target/xtensa-esp32s3-espidf/release/esp-pulser
